import { readFileSync } from "node:fs";
import path from "node:path";
import type { CitationMeta } from "@/types/docs";

type VersionEntry = {
  publishedAt: string;
  sourceCommit: string;
  previousCommit?: string;
};

/**
 * Extracts citation metadata for a canonical `.aide/docs/<slug>.md` file
 * by reading `.aide/versions.json` (generated by aide_upgrade).
 *
 * - publishedAt: ISO 8601 timestamp from versions.json
 * - sourceCommit: short SHA of the commit that produced this version
 * - versionedUrl: `/docs/<slug>?v=<sha>`
 *
 * Throws loudly if versions.json is missing or the slug has no entry —
 * this means aide_upgrade has not been run.
 */
export default function extractCitationMeta(slug: string): CitationMeta {
  const versionsPath = path.join(process.cwd(), ".aide", "versions.json");

  let versions: Record<string, VersionEntry>;
  try {
    versions = JSON.parse(readFileSync(versionsPath, "utf-8"));
  } catch {
    throw new Error(
      `extractCitationMeta: versions.json not found at "${versionsPath}" — run aide_upgrade`,
    );
  }

  const entry = versions[`docs/${slug}`];
  if (!entry) {
    throw new Error(
      `extractCitationMeta: no version entry for "${slug}" in versions.json — run aide_upgrade`,
    );
  }

  const { publishedAt, sourceCommit, previousCommit } = entry;
  const versionedUrl = `/docs/${slug}?v=${sourceCommit}`;

  return {
    publishedAt,
    sourceCommit,
    versionedUrl,
    previousCommit,
  };
}
