import { readFileSync } from "node:fs";
import path from "node:path";

type ArtifactCitationMeta = {
  publishedAt: string;
  sourceCommit: string;
  previousCommit?: string;
};

type VersionEntry = {
  publishedAt: string;
  sourceCommit: string;
  previousCommit?: string;
};

/** Derives the versions.json lookup key from the artifact's kind and slug. */
function resolveVersionKey(kind: string, slug: string): string {
  if (kind === "command") {
    if (slug === "aide") return "commands/aide/aide";
    return `commands/aide/${slug.replace(/^aide-/, "")}`;
  }
  if (kind === "agent") return `agents/aide/${slug}`;
  return `skills/${slug}`;
}

/**
 * Extracts citation metadata for a scaffold artifact by reading
 * `.aide/versions.json` (generated by aide_upgrade).
 *
 * - publishedAt: ISO 8601 timestamp from versions.json
 * - sourceCommit: short SHA of the upstream commit that produced this version
 * - previousCommit: short SHA of the prior version's commit (undefined when absent)
 *
 * Throws loudly if versions.json is missing or the artifact has no entry —
 * both indicate aide_upgrade has not been run or the artifact is untracked.
 */
export default function extractArtifactCitationMeta({
  slug,
  kind,
}: {
  slug: string;
  kind: string;
}): ArtifactCitationMeta {
  const versionsPath = path.join(process.cwd(), ".aide", "versions.json");

  let versions: Record<string, VersionEntry>;
  try {
    versions = JSON.parse(readFileSync(versionsPath, "utf-8"));
  } catch {
    throw new Error(
      `extractArtifactCitationMeta: versions.json not found at "${versionsPath}" — run aide_upgrade`,
    );
  }

  const key = resolveVersionKey(kind, slug);
  const entry = versions[key];
  if (!entry) {
    throw new Error(
      `extractArtifactCitationMeta: no version entry for key "${key}" (kind="${kind}", slug="${slug}") in versions.json — run aide_upgrade`,
    );
  }

  const { publishedAt, sourceCommit, previousCommit } = entry;

  return { publishedAt, sourceCommit, previousCommit };
}
